import {ApiProperty} from "@nestjs/swagger"
import {IsNumber, IsString, MaxLength} from "class-validator"
import {SetConfigDTOResponse} from "@/application/dto/set.config.dto";
import {Type} from "class-transformer";

export class AdjustCustomerPointResponseDataDTO {
  @ApiProperty({
    example: "8E5F0BM6YR",
    description: 'Reference Number of LinkAja',
    required: true,
    maxLength: 10
  })
  @MaxLength(10)
  @IsString()
  refNum: string

  @ApiProperty({
    example: 20211231,
    description: 'Expired date of LinkAja Bonus Balance Injected (YYYYMMDD)',
    required: true,
  })
  @IsNumber()
  expiredDate: number

  @ApiProperty({
    example: 10000000,
    description: 'Qouta of maximum LinkAJa Bonus Balance Injected',
    required: true,
  })
  @IsNumber()
  qouta: number

  @ApiProperty({
    example: 8955682,
    description: 'Remaining Account Balance of LinkAja Bonus Balance that the able to be injected',
    required: true,
  })
  @IsNumber()
  remaining: number
}


export class AdjustCustomerPointDTO {
  @ApiProperty({
    example: "LinkAJA0234o204i32434",
    description: 'Transaction ID generated by client application',
    required: true,
    maxLength: 25
  })
  @MaxLength(25)
  @IsString()
  trxId: string

  @ApiProperty({
    example: "6282117834375",
    description: `MSISDN that will be injected LinkAja Bonus Balance, prefix “62”`,
    required: true,
    maxLength: 15
  })
  @MaxLength(15)
  @IsString()
  msisdn: string

  @ApiProperty({
    example: 9,
    description: 'Nominal LinkAja Bonus Balance that will be injected to customer (max length = 10)',
    required: true,
    maxLength: 10
  })
  @IsNumber()
  amount: number

}


export class AdjustCustomerPointDTOResponse extends SetConfigDTOResponse {
  @ApiProperty({
    description: "Response of the value"
  })
  @Type(() => AdjustCustomerPointResponseDataDTO)
  payload: AdjustCustomerPointResponseDataDTO

  @ApiProperty({
    description: "Transaction ID from client application request",
    required: true
  })
  @IsNumber()
  trxid: number

  @ApiProperty({
    description: "LinkAja response time on nanosecond",
    required: true
  })
  @IsNumber()
  procTime: number
}


