import { ApiProperty } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { IsString } from 'class-validator';

import { SetConfigDTOResponse } from '@/application/dto/set.config.dto';

export class AssignVoucherResponseDataDTO {
  @ApiProperty({
    example: '2a8c1bb8-2d40-4b42-ba31-1f383a631f51',
    description: 'ID generated by client application',
    required: true,
  })
  @IsString()
  id: string;

  @ApiProperty({
    example: 'QA Gilga',
    description: 'title generated by client application',
    required: true,
  })
  @IsString()
  title: string;

  @ApiProperty({
    example: 'QAGILGA-R2ZMFJYERGEN',
    description: 'code generated by client application',
    required: true,
  })
  @IsString()
  code: string;

  @ApiProperty({
    example: 100,
    description: 'maxReward generated by client application',
    required: true,
  })
  @IsString()
  maxReward: number;

  @ApiProperty({
    example: '2022-08-29T03:07:25+07:00',
    description: 'Start At generated by client application',
    required: true,
  })
  @IsString()
  startAt: string;

  @ApiProperty({
    example: '2022-12-12T23:59:59+07:00',
    description: 'End At generated by client application',
    required: true,
  })
  @IsString()
  endAt: string;
}

export class AssignVoucherDTO {
  @ApiProperty({
    example: 'c69d71ab-7ac5-4923-9961-6b32133c4425',
    description: 'Transaction ID generated by client application',
    required: true,
  })
  @IsString()
  transactionId: string;

  @ApiProperty({
    example: '6282117834375',
    description: `MSISDN  prefix “62”`,
    required: true,
  })
  @IsString()
  msisdn: number;

  @ApiProperty({
    example: 'b8c705ff-012b-40fd-a4ed-67b84019c928',
    description: 'Partner Voucher ID generated by client application',
    required: true,
  })
  @IsString()
  partnerVoucherId: string;

  @ApiProperty({
    example: '2023-12-12',
    description: 'Exp Date',
    required: false,
  })
  @IsString()
  expiryDate: string;
}

export class AssignVoucherDTOResponse extends SetConfigDTOResponse {
  @ApiProperty({
    description: 'ID generated by client application',
  })
  @IsString()
  id: string;

  @ApiProperty({
    description: 'Transaction ID generated by client application',
  })
  @IsString()
  transactionId: string;

  @ApiProperty({
    description: 'MSISDN prefix “62”',
  })
  msisdn: any;

  @ApiProperty({
    description: 'Date create data from client application',
  })
  @IsString()
  createdAt: string;

  @ApiProperty({
    description: 'Response of the value',
  })
  @Type(() => AssignVoucherResponseDataDTO)
  voucher: AssignVoucherResponseDataDTO;

  xid: any;
}

export class AssignVoucherLinkAjaDTOResponse {
  @ApiProperty({
    description: 'ID generated by client application',
  })
  @IsString()
  id: string;

  @ApiProperty({
    description: 'Transaction ID generated by client application',
  })
  @IsString()
  transactionId: string;

  @ApiProperty({
    description: 'MSISDN prefix “62”',
  })
  msisdn: any;

  @ApiProperty({
    description: 'Date create data from client application',
  })
  @IsString()
  createdAt: string;

  @ApiProperty({
    description: 'Response of the value',
  })
  @Type(() => AssignVoucherResponseDataDTO)
  voucher: AssignVoucherResponseDataDTO;
  xid: any;

  @ApiProperty({ example: 200 })
  status: any;

  @ApiProperty({ example: 'CONFIG_SYSTEM_UPDATE' })
  @IsString()
  transaction_classify: string;

  @ApiProperty({ example: 'Application Config Updated Successfully' })
  @IsString()
  message: string;

  payload: any;
}
