export const NOTIFICATION_TEMPLATE_REDEEM_SUCCESS_CAMPAIGN = "NOTIFICATION_GROUP_REDEEM_SUCCESS_CAMPAIGN"
export const NOTIFICATION_TEMPLATE_REDEEM_SUCCESS_INTERNAL = "NOTIFICATION_GROUP_REDEEM_SUCCESS_INTERNAL"

export const NOTIFICATION_TYPE =
  [
    'SMS',
    'Email',
    'MyTelkomsel-Push Notification',
    'MyTelkomsel-Inbox'
  ]
