export enum EventCodeEnum {
  REV_MULTIPLY_POINT = 'REV-MULTIPLY-POINT',
  REV_MULTIPLY_TRX = 'REV-MULTIPLY-TRX',
  REV_NO_MULTIPLY_POINT = 'REV-NO-MULTIPLY-POINT',
  REV_NO_MULTIPLY_TRX = 'REV-NO-MULTIPLY-TRX',
  REV_MULTIPLY_TRX_DEFAULT = 'REV-MULTIPLY-TRX-DEFAULT',
}
