export enum CouponNotifTemplate {
  INJECT_COUPON_SUCCESS = "NOTIFICATION_GROUP_INJECT_COUPON_SUCCESS_CUSTOMER",
  INJECT_COUPON_FAILED = "NOTIFICATION_GROUP_INJECT_COUPON_FAILED_CUSTOMER",
  INJECT_COUPON_INVALID_ENPOINT = "NOTIFICATION_GROUP_INJECT_COUPON_INVALID_ENPOINT",
  REDEEM_SUCCESS = "NOTIFICATION_GROUP_REDEEM_SUCCESS_CUSTOMER",
  REDEEM_FAILED = "NOTIFICATION_GROUP_REDEEM_FAILED_CUSTOMER"
}
